### PR TITLE
Template Method

### PR DESCRIPTION
**Pull request by remlostime**
Add Template method in design pattern

- [x] Do not change the `.playground` nor `README.md` manually.
- [x] Go to `/source` and edit .swift files.
- [x] Run: `generate-playground.sh`

### CODE REVIEW

**Comment by remlostime** [comment]
#75

**Comment by ochococo** [comment]
@remlostime Rebase and `Run: generate-playground.sh`.

**Comment by remlostime** [comment]
@ochococo Rebased.

**Comment by ochococo** [comment]
Another rebase please 🙂

**Comment by ochococo** [comment]
After some thinking I don't see Template as particularly beneficial when we have such powerful protocols. Moreover, I see this pattern as almost harmful in Swift codebase. Inheritance from custom classed? Verboten.

**Pull request closed without merging**
