### PR TITLE
Fix Jedha spelling

### PR DESCRIPTION
**Pull request by otaviolima**
Source: http://www.starwars.com/databank/jedha

- [x] Do not change the `.playground` nor `README.md` manually.
- [x] Go to `/source` and edit .swift files.
- [x] Run: `generate-playground.sh`

### CODE REVIEW

**Comment by ochococo** [comment]
@otaviolima Rebase and `Run: generate-playground.sh`

**Comment by otaviolima** [comment]
@ochococo Done. :)

**Comment by ochococo** [comment]
Another one?

**Comment by otaviolima** [comment]
@ochococo Done ( =

**Comment by ochococo** [comment]
fixed on swift5 branch

**Pull request closed without merging**
