### PR TITLE
Add Flyweight pattern per issue #32

### PR DESCRIPTION
**Pull request by DavydLiu**
Aslo add a missing space in Virtual Proxy

### CODE REVIEW

**Comment by DavydLiu** [comment]
Any updates for this pull request?

**Comment by ochococo** [comment]
I will add this by hand cause repo file structure changed. Is that ok with you?

**Comment by DavydLiu** [comment]
Sure, let me know once it you added it. Thanks !

On Monday, September 7, 2015, Oktawian Chojnacki <notifications@github.com>
wrote:

> I will add this by hand cause repo file structure changed. Is that ok with
> you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ochococo/Design-Patterns-In-Swift/pull/44#issuecomment-138243758>
> .
>


-- 
Sent from Gmail Mobile

**Comment by ochococo** [comment]
Will try to do that tomorrow. Sorry 😞

**Comment by ochococo** [comment]
Done @DavydLiu

**Pull request closed without merging**
