### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kingreza**
added 'further examples' sub-heading. This way the cheatsheet can link to more in depth examples of each design pattern.

When you have more time you could add your examples!

### CODE REVIEW

**Comment by ochococo** [comment]
Just links to another repository. Is it really a value? I'm not so sure.
You could add more to this one. Add a value.
My idea - just improve descriptions here and then link - why not.

**Comment by kingreza** [comment]
The beauty of this cheatsheet is its brevity. It's to the point and clutter free. Each design pattern comes with a short description and a working example. Anyone who comes here can quickly get an understanding of how they can approach a pattern using Swift. 

Now with the option of adding further examples they can explore other projects that implement the design in more depth without adding clutter to the cheatsheet. 
 
thoughts?

**Comment by ochococo** [comment]
Ok. Let's do this. 

Please add all design patterns you have and we can merge. (don't forget to generate everything)

**Comment by ochococo** [comment]
This branch has conflicts that must be resolved @kingreza

**Comment by ochococo** [comment]
Can I ask you to resolve the conflicts? @kingreza

**Pull request closed without merging**
