### PR TITLE
Add a Chinese version & Translate complete.

### PR DESCRIPTION
**Pull request by Binlogo**
- [ ] Do not change the `.playground` nor `README.md` manually.
- [ ] Go to `/source` and edit .swift files.
- [ ] Run: `generate-playground.sh`

### CODE REVIEW

**Comment by ochococo** [comment]
Hej @Binlogo just make sure you've done everything right as the Playground file is autogenerated.

Vide:

- [] Do not change the `.playground` nor `README.md` manually.
- [] Go to `/source` and edit .swift files.
- [] Run: `generate-playground.sh`

**Comment by ochococo** [comment]
Thank you for contribution @Binlogo <3  , this PR has the highest priority, please update it and we can merge it right away.

**Comment by Binlogo** [comment]
Hi, @ochococo, sorry for the delay. But after update `/source` and edit `.swift` files, conflicts appeared. How to resolved it.
Otherwise, since it is another language version, should it merge to the same playground file or generate another?

**Comment by ochococo** [comment]
@Binlogo We could do it by:

- [ ]  Checkout current master
- [ ]  create `source_cn`
- [ ]  Copy and translate all folders and files from `source/*/*.swift`
- [ ] Let me know I'll update the rest (ex. generator)

**Comment by Binlogo** [comment]
@ochococo Alright and should I do something for help, if need, just comment.

**Pull request closed without merging**
