### PR TITLE
Format

### PR DESCRIPTION
**Pull request by remlostime**
Make the indent correct for state pattern

- [x] Do not change the `.playground` nor `README.md` manually.
- [x] Go to `/source` and edit .swift files.
- [x] Run: `generate-playground.sh`

### CODE REVIEW

**Comment by remlostime** [comment]
@ochococo Ping

**Comment by remlostime** [comment]
@ochococo PTAL

**Comment by ochococo** [comment]
Rebase?

**Comment by ochococo** [comment]
Fixed in swift5 branch.

**Pull request closed without merging**
