### PR TITLE
Removed .synchronize()

### PR DESCRIPTION
**Pull request by weitieda**
It's unnecessary to call `defaults.synchronize()` according to Apple's documentation. 
https://developer.apple.com/documentation/foundation/userdefaults/1414005-synchronize

### CODE REVIEW

**Comment by ochococo** [comment]
Thank you @weitieda, please take a look at https://github.com/ochococo/Design-Patterns-In-Swift/blob/master/GENERATE.md

**Comment by weitieda** [comment]
> Thank you @weitieda, please take a look at https://github.com/ochococo/Design-Patterns-In-Swift/blob/master/GENERATE.md

Sorry, I didn't realized there's a script. I'll update later then PR again.

**Comment by weitieda** [comment]
Updated it with the script :)

**Comment by ochococo** [comment]
@weitieda Perfect but after that you need to rebase to make sure we can merge without Github resolve trickery. Thank you so much 🙏

**Pull request closed without merging**
