### PR TITLE
Fixed compile error, spelling mistake, and a new pattern - Template

### PR DESCRIPTION
**Pull request by codethought**
- [X] Do not change the `.playground` nor `README.md` manually.
- [X] Go to `/source` and edit .swift files.
- [X] Run: `generate-playground.sh`

### CODE REVIEW

**Comment by ochococo** [comment]
Please rebase @codethought  <3

**Comment by codethought** [comment]
@ochococo  - done

**Comment by remlostime** [comment]
@ochococo I think this is a good update on playground. For now, the playground has the build error. Any update for this PR review?

**Comment by ochococo** [comment]
I will review it tomorrow.

**Comment by codethought** [comment]
@ochococo  any good news yet? ;)

**Comment by ochococo** [comment]
Awesome job @codethought !!! Sorry for the delay.

**Comment by codethought** [comment]
Thanks @ochococo  - glad to contribute, my friend.

**Pull request merged**
