### PR TITLE
[Issue-118] Replace `if let…` with `guard let…`

### PR DESCRIPTION
**Pull request by VladimirCreator**
- [x] Read [CONTRIBUTING.md](https://github.com/ochococo/Design-Patterns-In-Swift/blob/master/CONTRIBUTING.md)
- [x] Added description
- [x] Linked to and/or created issue

Issue #118.

# Description
Improves readability by reducing indenting's length.

### CODE REVIEW

**Comment by ochococo** [comment]
Thanks @VladimirCreator do you care enough to also update the Chinese version?

**Comment by VladimirCreator** [comment]
@ochococo You're welcome)

**Comment by VladimirCreator** [comment]
@ochococo Oh… :) I do not know. I updated the Chinese version as you asked. It's been a long and I thought that you'll not going to merge this pull request and closed it :/

**Comment by ochococo** [comment]
Sorry for the delay 🙏

**Comment by VladimirCreator** [comment]
@ochococo That's ok

**Pull request closed without merging**
