### PR TITLE
Add further example. update source to match README 

### PR DESCRIPTION
**Pull request by kingreza**
I added the new further examples. I also updated the source so the generated items match the recent pull requests that were only added to the readme file.

### CODE REVIEW

**Comment by ochococo** [comment]
Thanks for fixing the sources!

**Comment by ochococo** [comment]
Will have to run the Playground and see if nothing is broken and then I will merge it (today).

**Comment by ochococo** [comment]
Just add a new line at the end of the source file. Sorry for the inconvenience 😞 It's actually my fault.

**Comment by kingreza** [comment]
How does it look now?

**Comment by ochococo** [comment]
👏 Great!!!

**Pull request merged**
